[global]
config_version=3
backend=TensorRT
logging=no
default_slot=1
[slot_1]
profile_name=动画 24→60（推荐）
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=20
chain_1_max_fps=25
chain_1_rife=yes
chain_1_rife_model=426
chain_1_rife_factor_numerator=5
chain_1_rife_factor_denominator=2
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
chain_1_rife_before_upscale=yes
[slot_2]
profile_name=动画 24→48（最稳）
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=20
chain_1_max_fps=25
chain_1_rife=yes
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
chain_1_rife_before_upscale=yes
[slot_3]
profile_name=视频 30→60
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=26
chain_1_max_fps=31
chain_1_rife=yes
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
chain_1_rife_before_upscale=yes
[slot_4]
profile_name=动画 24→60（高质量）
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=20
chain_1_max_fps=25
chain_1_rife=yes
chain_1_rife_model=426
chain_1_rife_factor_numerator=5
chain_1_rife_factor_denominator=2
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=yes
chain_1_rife_before_upscale=yes
[slot_5]
profile_name=通用 2 倍补帧
chain_1_min_resolution=0x0
chain_1_max_resolution=0x0
chain_1_min_fps=0
chain_1_max_fps=0
chain_1_rife=yes
chain_1_rife_model=426
chain_1_rife_factor_numerator=2
chain_1_rife_factor_denominator=1
chain_1_rife_scene_detect_threshold=0.150
chain_1_rife_ensemble=no
chain_1_rife_before_upscale=yes
[slot_6]
profile_name=空白配置 6
[slot_7]
profile_name=空白配置 7
[slot_8]
profile_name=空白配置 8
[slot_9]
profile_name=空白配置 9
